### ISSUE TITLE
Command to bulk delete sessions

### ISSUE THREAD

**Issue by davidpottage** [ralish/PSPuTTYCfg#4]
Hello

I have too many putty sessions saved in my registry, mostly for machines that I only occasionally connect to. Now that I have PSPuTTYCfg and it is working reliably it would simplify my workflow if I only have commonly used sessions in my registry and the remainder are only saved as JSON files on disk ready to be reloaded as needed.

I am not sure how the command line might work. Perhaps:

    cat session_2_delete.txt | Delete-PuTTYSession -Registry -Force

or

    $Sessions = Import-PuTTYSession -Path $HOME\PuTTY_infrequently_used_sessions
    $Sessions | Delete-PuTTYSession -Registry -Force

**Comment by chrestomanci** [comment]
Sorry, I submitted the above issue while logged in via my work account. I am the same person that submitted issue #3

**Comment by ralish** [comment]
It turns out you can already do this, although it's a bit indirect. When you run `Import-PuTTYSession` the resulting sesssions have an `Origin` member which specifies the path of the session. That'll be either the path to the JSON file or the registry key, and so to remove sessions you can do something like this:

```
$Sessions = Import-PuTTYSession - Registry

# Remove all PuTTY sessions
$Sessions.Origin | Remove-Item -WhatIf

# Remove PuTTY sessions with 'Example' in their name
$Sessions | ? Name -match 'Example' | % { Remove-Item $_.Origin -WhatIf }

# Remove PuTTY sessions which don't have "Whatever", "Something", or "Else" in their name
$Sessions | ? Name -notmatch 'Whatever|Something|Else' | % { Remove-Item $_.Origin -WhatIf }
```

The above would also work for removing JSON files if the `Import-PuTTYSession` command was using `-Path` instead.

@chrestomanci Does this approach work for you? If not, can you provide more detail as to where it falls short.

**Comment by ralish** [comment]
@chrestomanci I'm closing this one for now but feel free to re-open if you have further questions or need additional input.
